package com.supra.imanager.dto;
// Generated Jun 1, 2018 7:55:07 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Restquicklink generated by hbm2java
 */
@Entity
@Table(name = "restquicklink")
public class Restquicklink implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4906134629841901843L;
	private int idrestquicklink;
	private String quicklinkid;
	private String quicklinkname;

	public Restquicklink() {
	}

	public Restquicklink(int idrestquicklink, String quicklinkid, String quicklinkname) {
		this.idrestquicklink = idrestquicklink;
		this.quicklinkid = quicklinkid;
		this.quicklinkname = quicklinkname;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "idrestquicklink", unique = true, nullable = false)
	public int getIdrestquicklink() {
		return this.idrestquicklink;
	}

	public void setIdrestquicklink(int idrestquicklink) {
		this.idrestquicklink = idrestquicklink;
	}

	@Column(name = "quicklinkid", nullable = false, length = 45)
	public String getQuicklinkid() {
		return this.quicklinkid;
	}

	public void setQuicklinkid(String quicklinkid) {
		this.quicklinkid = quicklinkid;
	}

	@Column(name = "quicklinkname", nullable = false, length = 45)
	public String getQuicklinkname() {
		return this.quicklinkname;
	}

	public void setQuicklinkname(String quicklinkname) {
		this.quicklinkname = quicklinkname;
	}

}
