package com.supra.imanager.dto;
// Generated Jun 1, 2018 7:55:07 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SupraEmpCompanyNotification generated by hbm2java
 */
@Entity
@Table(name = "supra_emp_company_notification")
public class SupraEmpCompanyNotification implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7856930818252369683L;
	private Long notificationrfnum;
	private String type;
	private String title;
	private String isActive;
	private String deleteflag;
	private String descrition;
	private String lastmodifiedby;
	private String policyGroup;
	private Date lastmodifiedon;
	private byte[] attachment;
	private String attachmentname;
	private String docextension;

	public SupraEmpCompanyNotification() {
	}

	public SupraEmpCompanyNotification(String type, String title, String isActive, String deleteflag, String descrition,
			String lastmodifiedby, String policyGroup, Date lastmodifiedon, byte[] attachment, String attachmentname,
			String docextension) {
		this.type = type;
		this.title = title;
		this.isActive = isActive;
		this.deleteflag = deleteflag;
		this.descrition = descrition;
		this.lastmodifiedby = lastmodifiedby;
		this.policyGroup = policyGroup;
		this.lastmodifiedon = lastmodifiedon;
		this.attachment = attachment;
		this.attachmentname = attachmentname;
		this.docextension = docextension;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "notificationrfnum", unique = true, nullable = false)
	public Long getNotificationrfnum() {
		return this.notificationrfnum;
	}

	public void setNotificationrfnum(Long notificationrfnum) {
		this.notificationrfnum = notificationrfnum;
	}

	@Column(name = "type", length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "title", length = 1000)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "isActive", length = 10)
	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	@Column(name = "deleteflag", length = 10)
	public String getDeleteflag() {
		return this.deleteflag;
	}

	public void setDeleteflag(String deleteflag) {
		this.deleteflag = deleteflag;
	}

	@Column(name = "descrition", length = 2000)
	public String getDescrition() {
		return this.descrition;
	}

	public void setDescrition(String descrition) {
		this.descrition = descrition;
	}

	@Column(name = "lastmodifiedby", length = 50)
	public String getLastmodifiedby() {
		return this.lastmodifiedby;
	}

	public void setLastmodifiedby(String lastmodifiedby) {
		this.lastmodifiedby = lastmodifiedby;
	}

	@Column(name = "policyGroup", length = 50)
	public String getPolicyGroup() {
		return this.policyGroup;
	}

	public void setPolicyGroup(String policyGroup) {
		this.policyGroup = policyGroup;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastmodifiedon", length = 19)
	public Date getLastmodifiedon() {
		return this.lastmodifiedon;
	}

	public void setLastmodifiedon(Date lastmodifiedon) {
		this.lastmodifiedon = lastmodifiedon;
	}

	@Column(name = "attachment")
	public byte[] getAttachment() {
		return this.attachment;
	}

	public void setAttachment(byte[] attachment) {
		this.attachment = attachment;
	}

	@Column(name = "attachmentname", length = 200)
	public String getAttachmentname() {
		return this.attachmentname;
	}

	public void setAttachmentname(String attachmentname) {
		this.attachmentname = attachmentname;
	}

	@Column(name = "docextension", length = 200)
	public String getDocextension() {
		return this.docextension;
	}

	public void setDocextension(String docextension) {
		this.docextension = docextension;
	}

}
