package com.supra.imanager.dto;
// Generated Jun 1, 2018 7:55:07 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SupraLeaveRequestMapping generated by hbm2java
 */
@Entity
@Table(name = "supra_leave_request_mapping")
public class SupraLeaveRequestMapping implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1092014951316797719L;
	private SupraLeaveRequestMappingId id;

	public SupraLeaveRequestMapping() {
	}

	public SupraLeaveRequestMapping(SupraLeaveRequestMappingId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "requestnumber", column = @Column(name = "requestnumber", length = 50)),
			@AttributeOverride(name = "leavecode", column = @Column(name = "leavecode")),
			@AttributeOverride(name = "username", column = @Column(name = "username", length = 50)),
			@AttributeOverride(name = "startdate", column = @Column(name = "startdate", length = 10)),
			@AttributeOverride(name = "enddate", column = @Column(name = "enddate", length = 10)),
			@AttributeOverride(name = "requestedby", column = @Column(name = "requestedby", length = 50)),
			@AttributeOverride(name = "creationdate", column = @Column(name = "creationdate", length = 10)),
			@AttributeOverride(name = "purpose", column = @Column(name = "purpose", length = 1000)),
			@AttributeOverride(name = "noofdays", column = @Column(name = "noofdays", precision = 22, scale = 0)),
			@AttributeOverride(name = "fulldayflag", column = @Column(name = "fulldayflag", length = 50)) })
	public SupraLeaveRequestMappingId getId() {
		return this.id;
	}

	public void setId(SupraLeaveRequestMappingId id) {
		this.id = id;
	}

}
