package com.supra.imanager.dto;
// Generated Jun 1, 2018 7:55:07 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SupraLeaveRequest generated by hbm2java
 */
@Entity
@Table(name = "supra_leave_request")
public class SupraLeaveRequest implements java.io.Serializable {

	private SupraLeaveRequestId id;

	public SupraLeaveRequest() {
	}

	public SupraLeaveRequest(SupraLeaveRequestId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "requestnumber", column = @Column(name = "requestnumber", nullable = false, length = 50)),
			@AttributeOverride(name = "totaldays", column = @Column(name = "totaldays", nullable = false, length = 50)),
			@AttributeOverride(name = "username", column = @Column(name = "username", nullable = false, length = 50)),
			@AttributeOverride(name = "createdon", column = @Column(name = "createdon", length = 10)),
			@AttributeOverride(name = "createdby", column = @Column(name = "createdby", length = 50)),
			@AttributeOverride(name = "approverRemark", column = @Column(name = "approverRemark", length = 250)),
			@AttributeOverride(name = "userreversalremark", column = @Column(name = "userreversalremark", length = 250)),
			@AttributeOverride(name = "status", column = @Column(name = "status", length = 50)),
			@AttributeOverride(name = "lastmodifiedby", column = @Column(name = "lastmodifiedby", length = 50)),
			@AttributeOverride(name = "lastmodifiedon", column = @Column(name = "lastmodifiedon", length = 50)),
			@AttributeOverride(name = "leaveyear", column = @Column(name = "leaveyear", length = 50)) })
	public SupraLeaveRequestId getId() {
		return this.id;
	}

	public void setId(SupraLeaveRequestId id) {
		this.id = id;
	}

}
