package com.supra.imanager.dto;
// Generated Jun 1, 2018 7:55:07 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SupraLeaveUserBalanceId generated by hbm2java
 */
@Embeddable
public class SupraLeaveUserBalanceId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6026667465712427258L;
	private String username;
	private String leavebandid;
	private Long leavecode;
	private String leavebalance;
	private String totalallotedleave;
	private String leaveyear;
	private String balanceupdationflag;
	private String lastmodifiedby;
	private Date lastmodifiedon;

	public SupraLeaveUserBalanceId() {
	}

	public SupraLeaveUserBalanceId(String username, String leavebandid, Long leavecode, String leavebalance,
			String totalallotedleave, String leaveyear, String balanceupdationflag, String lastmodifiedby,
			Date lastmodifiedon) {
		this.username = username;
		this.leavebandid = leavebandid;
		this.leavecode = leavecode;
		this.leavebalance = leavebalance;
		this.totalallotedleave = totalallotedleave;
		this.leaveyear = leaveyear;
		this.balanceupdationflag = balanceupdationflag;
		this.lastmodifiedby = lastmodifiedby;
		this.lastmodifiedon = lastmodifiedon;
	}

	@Column(name = "username", length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "leavebandid", length = 50)
	public String getLeavebandid() {
		return this.leavebandid;
	}

	public void setLeavebandid(String leavebandid) {
		this.leavebandid = leavebandid;
	}

	@Column(name = "leavecode")
	public Long getLeavecode() {
		return this.leavecode;
	}

	public void setLeavecode(Long leavecode) {
		this.leavecode = leavecode;
	}

	@Column(name = "leavebalance", length = 50)
	public String getLeavebalance() {
		return this.leavebalance;
	}

	public void setLeavebalance(String leavebalance) {
		this.leavebalance = leavebalance;
	}

	@Column(name = "totalallotedleave", length = 50)
	public String getTotalallotedleave() {
		return this.totalallotedleave;
	}

	public void setTotalallotedleave(String totalallotedleave) {
		this.totalallotedleave = totalallotedleave;
	}

	@Column(name = "leaveyear", length = 50)
	public String getLeaveyear() {
		return this.leaveyear;
	}

	public void setLeaveyear(String leaveyear) {
		this.leaveyear = leaveyear;
	}

	@Column(name = "balanceupdationflag", length = 5)
	public String getBalanceupdationflag() {
		return this.balanceupdationflag;
	}

	public void setBalanceupdationflag(String balanceupdationflag) {
		this.balanceupdationflag = balanceupdationflag;
	}

	@Column(name = "lastmodifiedby", length = 50)
	public String getLastmodifiedby() {
		return this.lastmodifiedby;
	}

	public void setLastmodifiedby(String lastmodifiedby) {
		this.lastmodifiedby = lastmodifiedby;
	}

	@Column(name = "lastmodifiedon", length = 19)
	public Date getLastmodifiedon() {
		return this.lastmodifiedon;
	}

	public void setLastmodifiedon(Date lastmodifiedon) {
		this.lastmodifiedon = lastmodifiedon;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SupraLeaveUserBalanceId))
			return false;
		SupraLeaveUserBalanceId castOther = (SupraLeaveUserBalanceId) other;

		return ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
				&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())))
				&& ((this.getLeavebandid() == castOther.getLeavebandid())
						|| (this.getLeavebandid() != null && castOther.getLeavebandid() != null
								&& this.getLeavebandid().equals(castOther.getLeavebandid())))
				&& ((this.getLeavecode() == castOther.getLeavecode()) || (this.getLeavecode() != null
						&& castOther.getLeavecode() != null && this.getLeavecode().equals(castOther.getLeavecode())))
				&& ((this.getLeavebalance() == castOther.getLeavebalance())
						|| (this.getLeavebalance() != null && castOther.getLeavebalance() != null
								&& this.getLeavebalance().equals(castOther.getLeavebalance())))
				&& ((this.getTotalallotedleave() == castOther.getTotalallotedleave())
						|| (this.getTotalallotedleave() != null && castOther.getTotalallotedleave() != null
								&& this.getTotalallotedleave().equals(castOther.getTotalallotedleave())))
				&& ((this.getLeaveyear() == castOther.getLeaveyear()) || (this.getLeaveyear() != null
						&& castOther.getLeaveyear() != null && this.getLeaveyear().equals(castOther.getLeaveyear())))
				&& ((this.getBalanceupdationflag() == castOther.getBalanceupdationflag())
						|| (this.getBalanceupdationflag() != null && castOther.getBalanceupdationflag() != null
								&& this.getBalanceupdationflag().equals(castOther.getBalanceupdationflag())))
				&& ((this.getLastmodifiedby() == castOther.getLastmodifiedby())
						|| (this.getLastmodifiedby() != null && castOther.getLastmodifiedby() != null
								&& this.getLastmodifiedby().equals(castOther.getLastmodifiedby())))
				&& ((this.getLastmodifiedon() == castOther.getLastmodifiedon())
						|| (this.getLastmodifiedon() != null && castOther.getLastmodifiedon() != null
								&& this.getLastmodifiedon().equals(castOther.getLastmodifiedon())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result + (getLeavebandid() == null ? 0 : this.getLeavebandid().hashCode());
		result = 37 * result + (getLeavecode() == null ? 0 : this.getLeavecode().hashCode());
		result = 37 * result + (getLeavebalance() == null ? 0 : this.getLeavebalance().hashCode());
		result = 37 * result + (getTotalallotedleave() == null ? 0 : this.getTotalallotedleave().hashCode());
		result = 37 * result + (getLeaveyear() == null ? 0 : this.getLeaveyear().hashCode());
		result = 37 * result + (getBalanceupdationflag() == null ? 0 : this.getBalanceupdationflag().hashCode());
		result = 37 * result + (getLastmodifiedby() == null ? 0 : this.getLastmodifiedby().hashCode());
		result = 37 * result + (getLastmodifiedon() == null ? 0 : this.getLastmodifiedon().hashCode());
		return result;
	}

}
