package com.supra.imanager.dto;
// Generated Jun 1, 2018 7:55:07 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SupraAccessgroupModulefunctionMapping generated by hbm2java
 */
@Entity
@Table(name = "supra_accessgroup_modulefunction_mapping")
public class SupraAccessgroupModulefunctionMapping implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3431872536888241212L;
	private SupraAccessgroupModulefunctionMappingId id;

	public SupraAccessgroupModulefunctionMapping() {
	}

	public SupraAccessgroupModulefunctionMapping(SupraAccessgroupModulefunctionMappingId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "functionid", column = @Column(name = "functionid", nullable = false)),
			@AttributeOverride(name = "groupid", column = @Column(name = "groupid", nullable = false)) })
	public SupraAccessgroupModulefunctionMappingId getId() {
		return this.id;
	}

	public void setId(SupraAccessgroupModulefunctionMappingId id) {
		this.id = id;
	}

}
