package com.supra.imanager.dto;
// Generated May 31, 2018 10:48:57 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SupraLoginHistory generated by hbm2java
 */
@Entity
@Table(name = "supra_login_history")
public class SupraLoginHistory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6134026121930235015L;
	private Long id;
	private String username;
	private String proxyloginby;
	private String loginlogoutflag;
	private Date loginlogouttime;

	public SupraLoginHistory() {
	}

	public SupraLoginHistory(String username, String loginlogoutflag, Date loginlogouttime) {
		this.username = username;
		this.loginlogoutflag = loginlogoutflag;
		this.loginlogouttime = loginlogouttime;
	}

	public SupraLoginHistory(String username, String proxyloginby, String loginlogoutflag, Date loginlogouttime) {
		this.username = username;
		this.proxyloginby = proxyloginby;
		this.loginlogoutflag = loginlogoutflag;
		this.loginlogouttime = loginlogouttime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "proxyloginby", length = 50)
	public String getProxyloginby() {
		return this.proxyloginby;
	}

	public void setProxyloginby(String proxyloginby) {
		this.proxyloginby = proxyloginby;
	}

	@Column(name = "loginlogoutflag", nullable = false, length = 50)
	public String getLoginlogoutflag() {
		return this.loginlogoutflag;
	}

	public void setLoginlogoutflag(String loginlogoutflag) {
		this.loginlogoutflag = loginlogoutflag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "loginlogouttime", nullable = false, length = 19)
	public Date getLoginlogouttime() {
		return this.loginlogouttime;
	}

	public void setLoginlogouttime(Date loginlogouttime) {
		this.loginlogouttime = loginlogouttime;
	}

}
