package com.supra.imanager.dto;
// Generated Jun 1, 2018 7:55:07 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SupraAppModule generated by hbm2java
 */
@Entity
@Table(name = "supra_app_module")
public class SupraAppModule implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8424173090448267459L;
	private Long moduleid;
	private String modulename;

	public SupraAppModule() {
	}

	public SupraAppModule(String modulename) {
		this.modulename = modulename;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "moduleid", unique = true, nullable = false)
	public Long getModuleid() {
		return this.moduleid;
	}

	public void setModuleid(Long moduleid) {
		this.moduleid = moduleid;
	}

	@Column(name = "modulename", nullable = false, length = 50)
	public String getModulename() {
		return this.modulename;
	}

	public void setModulename(String modulename) {
		this.modulename = modulename;
	}

}
