package com.supra.imanager.dto;
// Generated Jun 1, 2018 7:55:07 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SupraLeaveRequestId generated by hbm2java
 */
@Embeddable
public class SupraLeaveRequestId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3606695986877758330L;
	private String requestnumber;
	private String totaldays;
	private String username;
	private Date createdon;
	private String createdby;
	private String approverRemark;
	private String userreversalremark;
	private String status;
	private String lastmodifiedby;
	private String lastmodifiedon;
	private String leaveyear;

	public SupraLeaveRequestId() {
	}

	public SupraLeaveRequestId(String requestnumber, String totaldays, String username) {
		this.requestnumber = requestnumber;
		this.totaldays = totaldays;
		this.username = username;
	}

	public SupraLeaveRequestId(String requestnumber, String totaldays, String username, Date createdon,
			String createdby, String approverRemark, String userreversalremark, String status, String lastmodifiedby,
			String lastmodifiedon, String leaveyear) {
		this.requestnumber = requestnumber;
		this.totaldays = totaldays;
		this.username = username;
		this.createdon = createdon;
		this.createdby = createdby;
		this.approverRemark = approverRemark;
		this.userreversalremark = userreversalremark;
		this.status = status;
		this.lastmodifiedby = lastmodifiedby;
		this.lastmodifiedon = lastmodifiedon;
		this.leaveyear = leaveyear;
	}

	@Column(name = "requestnumber", nullable = false, length = 50)
	public String getRequestnumber() {
		return this.requestnumber;
	}

	public void setRequestnumber(String requestnumber) {
		this.requestnumber = requestnumber;
	}

	@Column(name = "totaldays", nullable = false, length = 50)
	public String getTotaldays() {
		return this.totaldays;
	}

	public void setTotaldays(String totaldays) {
		this.totaldays = totaldays;
	}

	@Column(name = "username", nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "createdon", length = 10)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Column(name = "createdby", length = 50)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "approverRemark", length = 250)
	public String getApproverRemark() {
		return this.approverRemark;
	}

	public void setApproverRemark(String approverRemark) {
		this.approverRemark = approverRemark;
	}

	@Column(name = "userreversalremark", length = 250)
	public String getUserreversalremark() {
		return this.userreversalremark;
	}

	public void setUserreversalremark(String userreversalremark) {
		this.userreversalremark = userreversalremark;
	}

	@Column(name = "status", length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "lastmodifiedby", length = 50)
	public String getLastmodifiedby() {
		return this.lastmodifiedby;
	}

	public void setLastmodifiedby(String lastmodifiedby) {
		this.lastmodifiedby = lastmodifiedby;
	}

	@Column(name = "lastmodifiedon", length = 50)
	public String getLastmodifiedon() {
		return this.lastmodifiedon;
	}

	public void setLastmodifiedon(String lastmodifiedon) {
		this.lastmodifiedon = lastmodifiedon;
	}

	@Column(name = "leaveyear", length = 50)
	public String getLeaveyear() {
		return this.leaveyear;
	}

	public void setLeaveyear(String leaveyear) {
		this.leaveyear = leaveyear;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SupraLeaveRequestId))
			return false;
		SupraLeaveRequestId castOther = (SupraLeaveRequestId) other;

		return ((this.getRequestnumber() == castOther.getRequestnumber())
				|| (this.getRequestnumber() != null && castOther.getRequestnumber() != null
						&& this.getRequestnumber().equals(castOther.getRequestnumber())))
				&& ((this.getTotaldays() == castOther.getTotaldays()) || (this.getTotaldays() != null
						&& castOther.getTotaldays() != null && this.getTotaldays().equals(castOther.getTotaldays())))
				&& ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
						&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())))
				&& ((this.getCreatedon() == castOther.getCreatedon()) || (this.getCreatedon() != null
						&& castOther.getCreatedon() != null && this.getCreatedon().equals(castOther.getCreatedon())))
				&& ((this.getCreatedby() == castOther.getCreatedby()) || (this.getCreatedby() != null
						&& castOther.getCreatedby() != null && this.getCreatedby().equals(castOther.getCreatedby())))
				&& ((this.getApproverRemark() == castOther.getApproverRemark())
						|| (this.getApproverRemark() != null && castOther.getApproverRemark() != null
								&& this.getApproverRemark().equals(castOther.getApproverRemark())))
				&& ((this.getUserreversalremark() == castOther.getUserreversalremark())
						|| (this.getUserreversalremark() != null && castOther.getUserreversalremark() != null
								&& this.getUserreversalremark().equals(castOther.getUserreversalremark())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& ((this.getLastmodifiedby() == castOther.getLastmodifiedby())
						|| (this.getLastmodifiedby() != null && castOther.getLastmodifiedby() != null
								&& this.getLastmodifiedby().equals(castOther.getLastmodifiedby())))
				&& ((this.getLastmodifiedon() == castOther.getLastmodifiedon())
						|| (this.getLastmodifiedon() != null && castOther.getLastmodifiedon() != null
								&& this.getLastmodifiedon().equals(castOther.getLastmodifiedon())))
				&& ((this.getLeaveyear() == castOther.getLeaveyear()) || (this.getLeaveyear() != null
						&& castOther.getLeaveyear() != null && this.getLeaveyear().equals(castOther.getLeaveyear())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRequestnumber() == null ? 0 : this.getRequestnumber().hashCode());
		result = 37 * result + (getTotaldays() == null ? 0 : this.getTotaldays().hashCode());
		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result + (getCreatedon() == null ? 0 : this.getCreatedon().hashCode());
		result = 37 * result + (getCreatedby() == null ? 0 : this.getCreatedby().hashCode());
		result = 37 * result + (getApproverRemark() == null ? 0 : this.getApproverRemark().hashCode());
		result = 37 * result + (getUserreversalremark() == null ? 0 : this.getUserreversalremark().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getLastmodifiedby() == null ? 0 : this.getLastmodifiedby().hashCode());
		result = 37 * result + (getLastmodifiedon() == null ? 0 : this.getLastmodifiedon().hashCode());
		result = 37 * result + (getLeaveyear() == null ? 0 : this.getLeaveyear().hashCode());
		return result;
	}

}
