package com.supra.imanager.dto;
// Generated Jun 1, 2018 7:55:07 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SupraAccessgroupUserMapping generated by hbm2java
 */
@Entity
@Table(name = "supra_accessgroup_user_mapping")
public class SupraAccessgroupUserMapping implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8451279244090731476L;
	private SupraAccessgroupUserMappingId id;

	public SupraAccessgroupUserMapping() {
	}

	public SupraAccessgroupUserMapping(SupraAccessgroupUserMappingId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "groupid", column = @Column(name = "groupid", nullable = false)),
			@AttributeOverride(name = "username", column = @Column(name = "username", nullable = false, length = 50)) })
	public SupraAccessgroupUserMappingId getId() {
		return this.id;
	}

	public void setId(SupraAccessgroupUserMappingId id) {
		this.id = id;
	}

}
