package com.supra.imanager.dto;
// Generated Jun 1, 2018 7:55:07 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SupraAccessgroupUserMappingId generated by hbm2java
 */
@Embeddable
public class SupraAccessgroupUserMappingId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2646263769734056419L;
	private long groupid;
	private String username;

	public SupraAccessgroupUserMappingId() {
	}

	public SupraAccessgroupUserMappingId(long groupid, String username) {
		this.groupid = groupid;
		this.username = username;
	}

	@Column(name = "groupid", nullable = false)
	public long getGroupid() {
		return this.groupid;
	}

	public void setGroupid(long groupid) {
		this.groupid = groupid;
	}

	@Column(name = "username", nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SupraAccessgroupUserMappingId))
			return false;
		SupraAccessgroupUserMappingId castOther = (SupraAccessgroupUserMappingId) other;

		return (this.getGroupid() == castOther.getGroupid())
				&& ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
						&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getGroupid();
		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		return result;
	}

}
