package com.supra.imanager.dto;
// Generated Jun 1, 2018 7:55:07 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * SupraLeaveType generated by hbm2java
 */
@Entity
@Table(name = "supra_leave_type",uniqueConstraints = @UniqueConstraint(columnNames = "leavename"))
public class SupraLeaveType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5557442880343712112L;
	private Integer leavecode;
	private String leavename;
	private String leavegroup;
	private String leavedesc;
	private String addedby;
	private Date addedon;
	private String activeflag;
	private String policyGroup;
	private String applyBeforeDays;
	private String maxDaysPerRequest;
	private String cumulativegroup;
	private String applyByHr;
	private String applyByManager;
	private String applyByAdmin;

	public SupraLeaveType() {
	}

	public SupraLeaveType(String leavename, String leavegroup, String leavedesc, String addedby, Date addedon,
			String activeflag, String maxDaysPerRequest, String cumulativegroup, String applyByHr,
			String applyByManager, String applyByAdmin) {
		this.leavename = leavename;
		this.leavegroup = leavegroup;
		this.leavedesc = leavedesc;
		this.addedby = addedby;
		this.addedon = addedon;
		this.activeflag = activeflag;
		this.maxDaysPerRequest = maxDaysPerRequest;
		this.cumulativegroup = cumulativegroup;
		this.applyByHr = applyByHr;
		this.applyByManager = applyByManager;
		this.applyByAdmin = applyByAdmin;
	}

	public SupraLeaveType(String leavename, String leavegroup, String leavedesc, String addedby, Date addedon,
			String activeflag, String policyGroup, String applyBeforeDays, String maxDaysPerRequest,
			String cumulativegroup, String applyByHr, String applyByManager, String applyByAdmin) {
		this.leavename = leavename;
		this.leavegroup = leavegroup;
		this.leavedesc = leavedesc;
		this.addedby = addedby;
		this.addedon = addedon;
		this.activeflag = activeflag;
		this.policyGroup = policyGroup;
		this.applyBeforeDays = applyBeforeDays;
		this.maxDaysPerRequest = maxDaysPerRequest;
		this.cumulativegroup = cumulativegroup;
		this.applyByHr = applyByHr;
		this.applyByManager = applyByManager;
		this.applyByAdmin = applyByAdmin;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "leavecode", unique = true, nullable = false)
	public Integer getLeavecode() {
		return this.leavecode;
	}

	public void setLeavecode(Integer leavecode) {
		this.leavecode = leavecode;
	}

	@Column(name = "leavename", unique = true, nullable = false, length = 100)
	public String getLeavename() {
		return this.leavename;
	}

	public void setLeavename(String leavename) {
		this.leavename = leavename;
	}

	@Column(name = "leavegroup", nullable = false, length = 100)
	public String getLeavegroup() {
		return this.leavegroup;
	}

	public void setLeavegroup(String leavegroup) {
		this.leavegroup = leavegroup;
	}

	@Column(name = "leavedesc", nullable = false, length = 250)
	public String getLeavedesc() {
		return this.leavedesc;
	}

	public void setLeavedesc(String leavedesc) {
		this.leavedesc = leavedesc;
	}

	@Column(name = "addedby", nullable = false, length = 100)
	public String getAddedby() {
		return this.addedby;
	}

	public void setAddedby(String addedby) {
		this.addedby = addedby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "addedon", nullable = false, length = 10)
	public Date getAddedon() {
		return this.addedon;
	}

	public void setAddedon(Date addedon) {
		this.addedon = addedon;
	}

	@Column(name = "activeflag", nullable = false, length = 50)
	public String getActiveflag() {
		return this.activeflag;
	}

	public void setActiveflag(String activeflag) {
		this.activeflag = activeflag;
	}

	@Column(name = "policyGroup", length = 100)
	public String getPolicyGroup() {
		return this.policyGroup;
	}

	public void setPolicyGroup(String policyGroup) {
		this.policyGroup = policyGroup;
	}

	@Column(name = "applyBeforeDays", length = 50)
	public String getApplyBeforeDays() {
		return this.applyBeforeDays;
	}

	public void setApplyBeforeDays(String applyBeforeDays) {
		this.applyBeforeDays = applyBeforeDays;
	}

	@Column(name = "maxDaysPerRequest", nullable = false, length = 50)
	public String getMaxDaysPerRequest() {
		return this.maxDaysPerRequest;
	}

	public void setMaxDaysPerRequest(String maxDaysPerRequest) {
		this.maxDaysPerRequest = maxDaysPerRequest;
	}

	@Column(name = "cumulativegroup", nullable = false, length = 50)
	public String getCumulativegroup() {
		return this.cumulativegroup;
	}

	public void setCumulativegroup(String cumulativegroup) {
		this.cumulativegroup = cumulativegroup;
	}

	@Column(name = "applyByHR", nullable = false, length = 2)
	public String getApplyByHr() {
		return this.applyByHr;
	}

	public void setApplyByHr(String applyByHr) {
		this.applyByHr = applyByHr;
	}

	@Column(name = "applyByManager", nullable = false, length = 2)
	public String getApplyByManager() {
		return this.applyByManager;
	}

	public void setApplyByManager(String applyByManager) {
		this.applyByManager = applyByManager;
	}

	@Column(name = "applyByAdmin", nullable = false, length = 2)
	public String getApplyByAdmin() {
		return this.applyByAdmin;
	}

	public void setApplyByAdmin(String applyByAdmin) {
		this.applyByAdmin = applyByAdmin;
	}

}
