package com.supra.imanager.dto;
// Generated Jun 1, 2018 7:55:07 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SupraLeaveRequestMappingId generated by hbm2java
 */
@Embeddable
public class SupraLeaveRequestMappingId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -864645615884500052L;
	private String requestnumber;
	private Long leavecode;
	private String username;
	private Date startdate;
	private Date enddate;
	private String requestedby;
	private Date creationdate;
	private String purpose;
	private Double noofdays;
	private String fulldayflag;

	public SupraLeaveRequestMappingId() {
	}

	public SupraLeaveRequestMappingId(String requestnumber, Long leavecode, String username, Date startdate,
			Date enddate, String requestedby, Date creationdate, String purpose, Double noofdays, String fulldayflag) {
		this.requestnumber = requestnumber;
		this.leavecode = leavecode;
		this.username = username;
		this.startdate = startdate;
		this.enddate = enddate;
		this.requestedby = requestedby;
		this.creationdate = creationdate;
		this.purpose = purpose;
		this.noofdays = noofdays;
		this.fulldayflag = fulldayflag;
	}

	@Column(name = "requestnumber", length = 50)
	public String getRequestnumber() {
		return this.requestnumber;
	}

	public void setRequestnumber(String requestnumber) {
		this.requestnumber = requestnumber;
	}

	@Column(name = "leavecode")
	public Long getLeavecode() {
		return this.leavecode;
	}

	public void setLeavecode(Long leavecode) {
		this.leavecode = leavecode;
	}

	@Column(name = "username", length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "startdate", length = 10)
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@Column(name = "enddate", length = 10)
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	@Column(name = "requestedby", length = 50)
	public String getRequestedby() {
		return this.requestedby;
	}

	public void setRequestedby(String requestedby) {
		this.requestedby = requestedby;
	}

	@Column(name = "creationdate", length = 10)
	public Date getCreationdate() {
		return this.creationdate;
	}

	public void setCreationdate(Date creationdate) {
		this.creationdate = creationdate;
	}

	@Column(name = "purpose", length = 1000)
	public String getPurpose() {
		return this.purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	@Column(name = "noofdays", precision = 22, scale = 0)
	public Double getNoofdays() {
		return this.noofdays;
	}

	public void setNoofdays(Double noofdays) {
		this.noofdays = noofdays;
	}

	@Column(name = "fulldayflag", length = 50)
	public String getFulldayflag() {
		return this.fulldayflag;
	}

	public void setFulldayflag(String fulldayflag) {
		this.fulldayflag = fulldayflag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SupraLeaveRequestMappingId))
			return false;
		SupraLeaveRequestMappingId castOther = (SupraLeaveRequestMappingId) other;

		return ((this.getRequestnumber() == castOther.getRequestnumber())
				|| (this.getRequestnumber() != null && castOther.getRequestnumber() != null
						&& this.getRequestnumber().equals(castOther.getRequestnumber())))
				&& ((this.getLeavecode() == castOther.getLeavecode()) || (this.getLeavecode() != null
						&& castOther.getLeavecode() != null && this.getLeavecode().equals(castOther.getLeavecode())))
				&& ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
						&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())))
				&& ((this.getStartdate() == castOther.getStartdate()) || (this.getStartdate() != null
						&& castOther.getStartdate() != null && this.getStartdate().equals(castOther.getStartdate())))
				&& ((this.getEnddate() == castOther.getEnddate()) || (this.getEnddate() != null
						&& castOther.getEnddate() != null && this.getEnddate().equals(castOther.getEnddate())))
				&& ((this.getRequestedby() == castOther.getRequestedby())
						|| (this.getRequestedby() != null && castOther.getRequestedby() != null
								&& this.getRequestedby().equals(castOther.getRequestedby())))
				&& ((this.getCreationdate() == castOther.getCreationdate())
						|| (this.getCreationdate() != null && castOther.getCreationdate() != null
								&& this.getCreationdate().equals(castOther.getCreationdate())))
				&& ((this.getPurpose() == castOther.getPurpose()) || (this.getPurpose() != null
						&& castOther.getPurpose() != null && this.getPurpose().equals(castOther.getPurpose())))
				&& ((this.getNoofdays() == castOther.getNoofdays()) || (this.getNoofdays() != null
						&& castOther.getNoofdays() != null && this.getNoofdays().equals(castOther.getNoofdays())))
				&& ((this.getFulldayflag() == castOther.getFulldayflag())
						|| (this.getFulldayflag() != null && castOther.getFulldayflag() != null
								&& this.getFulldayflag().equals(castOther.getFulldayflag())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRequestnumber() == null ? 0 : this.getRequestnumber().hashCode());
		result = 37 * result + (getLeavecode() == null ? 0 : this.getLeavecode().hashCode());
		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result + (getStartdate() == null ? 0 : this.getStartdate().hashCode());
		result = 37 * result + (getEnddate() == null ? 0 : this.getEnddate().hashCode());
		result = 37 * result + (getRequestedby() == null ? 0 : this.getRequestedby().hashCode());
		result = 37 * result + (getCreationdate() == null ? 0 : this.getCreationdate().hashCode());
		result = 37 * result + (getPurpose() == null ? 0 : this.getPurpose().hashCode());
		result = 37 * result + (getNoofdays() == null ? 0 : this.getNoofdays().hashCode());
		result = 37 * result + (getFulldayflag() == null ? 0 : this.getFulldayflag().hashCode());
		return result;
	}

}
