package com.supra.imanager.dto;
// Generated Jun 1, 2018 7:55:07 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * SupraUserPanelDisplayList generated by hbm2java
 */
@Entity
@Table(name = "supra_user_panel_display_list", uniqueConstraints = @UniqueConstraint(columnNames = {
		"panelid", "panelname", "username" }))
public class SupraUserPanelDisplayList implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -429075886379539873L;
	private Integer displayrfnum;
	private String panelid;
	private String panelname;
	private String username;
	private String viewflag;
	private String lastmodifiedby;
	private Date lastmodifiedon;

	public SupraUserPanelDisplayList() {
	}

	public SupraUserPanelDisplayList(String viewflag, Date lastmodifiedon) {
		this.viewflag = viewflag;
		this.lastmodifiedon = lastmodifiedon;
	}

	public SupraUserPanelDisplayList(String panelid, String panelname, String username, String viewflag,
			String lastmodifiedby, Date lastmodifiedon) {
		this.panelid = panelid;
		this.panelname = panelname;
		this.username = username;
		this.viewflag = viewflag;
		this.lastmodifiedby = lastmodifiedby;
		this.lastmodifiedon = lastmodifiedon;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "displayrfnum", unique = true, nullable = false)
	public Integer getDisplayrfnum() {
		return this.displayrfnum;
	}

	public void setDisplayrfnum(Integer displayrfnum) {
		this.displayrfnum = displayrfnum;
	}

	@Column(name = "panelid", length = 50)
	public String getPanelid() {
		return this.panelid;
	}

	public void setPanelid(String panelid) {
		this.panelid = panelid;
	}

	@Column(name = "panelname", length = 50)
	public String getPanelname() {
		return this.panelname;
	}

	public void setPanelname(String panelname) {
		this.panelname = panelname;
	}

	@Column(name = "username", length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "viewflag", nullable = false, length = 2)
	public String getViewflag() {
		return this.viewflag;
	}

	public void setViewflag(String viewflag) {
		this.viewflag = viewflag;
	}

	@Column(name = "lastmodifiedby", length = 50)
	public String getLastmodifiedby() {
		return this.lastmodifiedby;
	}

	public void setLastmodifiedby(String lastmodifiedby) {
		this.lastmodifiedby = lastmodifiedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastmodifiedon", nullable = false, length = 19)
	public Date getLastmodifiedon() {
		return this.lastmodifiedon;
	}

	public void setLastmodifiedon(Date lastmodifiedon) {
		this.lastmodifiedon = lastmodifiedon;
	}

}
