package com.supra.imanager.dto;
// Generated May 31, 2018 10:48:57 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Token generated by hbm2java
 */
@Entity
@Table(name = "Token")
public class Token implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8969099966605423223L;
	private int id;
	private String deviceName;
	private String deviceId;
	private String token;
	private String customerName;

	public Token() {
	}

	public Token(int id, String deviceName, String deviceId, String token, String customerName) {
		this.id = id;
		this.deviceName = deviceName;
		this.deviceId = deviceId;
		this.token = token;
		this.customerName = customerName;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "deviceName", nullable = false, length = 45)
	public String getDeviceName() {
		return this.deviceName;
	}

	public void setDeviceName(String deviceName) {
		this.deviceName = deviceName;
	}

	@Column(name = "deviceId", nullable = false, length = 45)
	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	@Column(name = "token", nullable = false, length = 45)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name = "customerName", nullable = false, length = 45)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

}
