package com.supra.imanager.dto;
// Generated May 31, 2018 10:48:57 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", uniqueConstraints = { @UniqueConstraint(columnNames = "primaryemail"),
		@UniqueConstraint(columnNames = "usercode") })
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6008778940982766608L;
	private Integer username;
	private String usercode;
	private String password;
	private String firstname;
	private String lastname;
	private String role;
	private String primaryemail;
	private String remark;
	private String usergroup;
	private String userstatus;
	private Date dob;
	private Date creationdate;
	private Date lastmodifieddate;
	private String reportingManager;
	private String hrManager;
	private Date joiningDate;
	private Date lastWorkingDate;
	private String baselocation;
	private String designation;
	private String accountunit;
	private String department;
	private String policygroup;

	public User() {
	}

	public User(String usercode, String password, String primaryemail) {
		this.usercode = usercode;
		this.password = password;
		this.primaryemail = primaryemail;
	}

	public User(String usercode, String password, String firstname, String lastname, String role, String primaryemail,
			String remark, String usergroup, String userstatus, Date dob, Date creationdate, Date lastmodifieddate,
			String reportingManager, String hrManager, Date joiningDate, Date lastWorkingDate, String baselocation,
			String designation, String accountunit, String department, String policygroup) {
		this.usercode = usercode;
		this.password = password;
		this.firstname = firstname;
		this.lastname = lastname;
		this.role = role;
		this.primaryemail = primaryemail;
		this.remark = remark;
		this.usergroup = usergroup;
		this.userstatus = userstatus;
		this.dob = dob;
		this.creationdate = creationdate;
		this.lastmodifieddate = lastmodifieddate;
		this.reportingManager = reportingManager;
		this.hrManager = hrManager;
		this.joiningDate = joiningDate;
		this.lastWorkingDate = lastWorkingDate;
		this.baselocation = baselocation;
		this.designation = designation;
		this.accountunit = accountunit;
		this.department = department;
		this.policygroup = policygroup;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "username", unique = true, nullable = false)
	public Integer getUsername() {
		return this.username;
	}

	public void setUsername(Integer username) {
		this.username = username;
	}

	@Column(name = "usercode", unique = true, nullable = false, length = 50)
	public String getUsercode() {
		return this.usercode;
	}

	public void setUsercode(String usercode) {
		this.usercode = usercode;
	}

	@Column(name = "password", nullable = false, length = 60)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "firstname", length = 50)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 50)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "role", length = 50)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "primaryemail", unique = true, nullable = false, length = 100)
	public String getPrimaryemail() {
		return this.primaryemail;
	}

	public void setPrimaryemail(String primaryemail) {
		this.primaryemail = primaryemail;
	}

	@Column(name = "remark", length = 250)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "usergroup", length = 100)
	public String getUsergroup() {
		return this.usergroup;
	}

	public void setUsergroup(String usergroup) {
		this.usergroup = usergroup;
	}

	@Column(name = "userstatus", length = 100)
	public String getUserstatus() {
		return this.userstatus;
	}

	public void setUserstatus(String userstatus) {
		this.userstatus = userstatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dob", length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "creationdate", length = 10)
	public Date getCreationdate() {
		return this.creationdate;
	}

	public void setCreationdate(Date creationdate) {
		this.creationdate = creationdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastmodifieddate", length = 19)
	public Date getLastmodifieddate() {
		return this.lastmodifieddate;
	}

	public void setLastmodifieddate(Date lastmodifieddate) {
		this.lastmodifieddate = lastmodifieddate;
	}

	@Column(name = "reportingManager", length = 50)
	public String getReportingManager() {
		return this.reportingManager;
	}

	public void setReportingManager(String reportingManager) {
		this.reportingManager = reportingManager;
	}

	@Column(name = "hrManager", length = 50)
	public String getHrManager() {
		return this.hrManager;
	}

	public void setHrManager(String hrManager) {
		this.hrManager = hrManager;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "joiningDate", length = 10)
	public Date getJoiningDate() {
		return this.joiningDate;
	}

	public void setJoiningDate(Date joiningDate) {
		this.joiningDate = joiningDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "lastWorkingDate", length = 10)
	public Date getLastWorkingDate() {
		return this.lastWorkingDate;
	}

	public void setLastWorkingDate(Date lastWorkingDate) {
		this.lastWorkingDate = lastWorkingDate;
	}

	@Column(name = "baselocation", length = 100)
	public String getBaselocation() {
		return this.baselocation;
	}

	public void setBaselocation(String baselocation) {
		this.baselocation = baselocation;
	}

	@Column(name = "designation", length = 100)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "accountunit", length = 100)
	public String getAccountunit() {
		return this.accountunit;
	}

	public void setAccountunit(String accountunit) {
		this.accountunit = accountunit;
	}

	@Column(name = "department", length = 100)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "policygroup", length = 100)
	public String getPolicygroup() {
		return this.policygroup;
	}

	public void setPolicygroup(String policygroup) {
		this.policygroup = policygroup;
	}

}
