package com.supra.imanager.dto;
// Generated Jun 1, 2018 7:55:07 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewSupraUserStatus generated by hbm2java
 */
@Entity
@Table(name = "VIEW_SUPRA_USER_STATUS")
public class ViewSupraUserStatus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2244651281020036104L;
	private ViewSupraUserStatusId id;

	public ViewSupraUserStatus() {
	}

	public ViewSupraUserStatus(ViewSupraUserStatusId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "module", column = @Column(name = "module", nullable = false, length = 13)),
			@AttributeOverride(name = "statuscount", column = @Column(name = "statuscount", nullable = false)),
			@AttributeOverride(name = "status", column = @Column(name = "status", length = 50)),
			@AttributeOverride(name = "username", column = @Column(name = "username", length = 50)) })
	public ViewSupraUserStatusId getId() {
		return this.id;
	}

	public void setId(ViewSupraUserStatusId id) {
		this.id = id;
	}

}
